using System.Linq;
using NeonRift.Frontend;
using NeonRift.Vehicles;
using NUnit.Framework;
using Unity.Cinemachine;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.UIElements;

namespace NeonRift.Tests
{
    /// <summary>Car Select garage: scene wiring (generated by GarageBuilder) and the catalog data it presents.</summary>
    public sealed class CarSelectTests
    {
        [Test]
        public void CatalogVehicles_HaveCarSelectData()
        {
            var catalog = AssetDatabase.LoadAssetAtPath<VehicleCatalog>("Assets/_NeonRift/Data/Vehicles/VehicleCatalog.asset");
            Assert.IsNotNull(catalog);
            Assert.GreaterOrEqual(catalog.Count, 3);
            foreach (var v in catalog.Vehicles)
            {
                Assert.IsFalse(string.IsNullOrWhiteSpace(v.Category), $"{v.Id} category");
                Assert.IsFalse(string.IsNullOrWhiteSpace(v.Description), $"{v.Id} description");
                Assert.IsFalse(v.DisplayStatsProvisional, $"{v.Id} stats must be measured from physics");
                var s = v.DisplayStats;
                Assert.That(s.brakingDistanceMetres, Is.InRange(20f, 60f), $"{v.Id} braking 100-0 measured");
                Assert.That(s.zeroToHundredSeconds, Is.InRange(1.5f, 10f), $"{v.Id} 0-100");
                Assert.AreNotEqual("—", v.DrivetrainLabel, $"{v.Id} drivetrain from the physics profile");
                Assert.IsNotNull(v.AudioProfile, $"{v.Id} audio profile (showroom engine)");
            }
        }

        [Test]
        public void CarSelectScene_IsAWiredGarage()
        {
            var scene = EditorSceneManager.OpenScene("Assets/_NeonRift/Scenes/CarSelect.unity", OpenSceneMode.Additive);
            try
            {
                var roots = scene.GetRootGameObjects();
                var screen = roots.SelectMany(r => r.GetComponentsInChildren<CarSelectScreen>(true)).Single();
                var doc = screen.GetComponent<UIDocument>();
                Assert.IsNotNull(doc.panelSettings);
                Assert.IsNotNull(doc.visualTreeAsset);
                var showroom = (VehicleShowroom)new SerializedObject(screen).FindProperty("showroom").objectReferenceValue;
                Assert.IsNotNull(showroom, "screen → showroom");
                var so = new SerializedObject(showroom);
                foreach (var field in new[] { "turntable", "engine", "door", "heroCamera", "swapCamera", "departCamera", "openingCamera" })
                    Assert.IsNotNull(so.FindProperty(field).objectReferenceValue, $"showroom.{field}");
                Assert.AreEqual(2, so.FindProperty("parkedSlots").arraySize, "two parking bays for the cars not chosen");
                Assert.GreaterOrEqual(so.FindProperty("stageLights").arraySize, 3, "key + rims");
                var engine = (ShowroomEngine)so.FindProperty("engine").objectReferenceValue;
                Assert.IsNotNull(new SerializedObject(engine).FindProperty("output").objectReferenceValue, "engine routed into the mixer");
                // Rendering: a brain on the main camera, a post-process volume, a baked reflection probe.
                var cam = roots.SelectMany(r => r.GetComponentsInChildren<Camera>(true)).Single(c => c.CompareTag("MainCamera"));
                Assert.IsNotNull(cam.GetComponent<CinemachineBrain>());
                Assert.IsTrue(roots.SelectMany(r => r.GetComponentsInChildren<Volume>(true)).Any(v => v.isGlobal && v.sharedProfile != null));
                var probe = roots.SelectMany(r => r.GetComponentsInChildren<ReflectionProbe>(true)).Single();
                Assert.IsNotNull(probe.customBakedTexture, "garage reflection probe is baked");
                // The hero camera is the live one when the scene opens.
                var hero = (CinemachineCamera)so.FindProperty("heroCamera").objectReferenceValue;
                Assert.Greater(hero.Priority.Value, ((CinemachineCamera)so.FindProperty("departCamera").objectReferenceValue).Priority.Value);
            }
            finally
            {
                EditorSceneManager.CloseScene(scene, true);
            }
        }
    }
}
